site_name: Zero Trust IoT Library
site_description: Centralized technical documentation
repo_url: https://github.com/arun-dot-com/automated-documentation
repo_name: automated-documentation
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
extra:
  logo: asset/logo.png
  #favicon: assets/zerotrustiot-favicon.ico
plugins:
  - search

nav:
  - Home: index.md
  - Activity Log: activity.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true
